on:
  push:
    branches:
      - master 




jobs:
  build:
    runs-on: macos-latest


    steps:
      - name: 'Testing github action'
        run: pwd

      - name: 'Testing printing'
        run: echo Malk



